[[ -s "$HOME/.dcp/commonrc" ]] && source "$HOME/.dcp/commonrc"
set_prompt

# Command not found hook for Arch Linux
[[ -s "/usr/share/doc/pkgfile/command-not-found.bash" ]] &&
  source "/usr/share/doc/pkgfile/command-not-found.bash"
