# Load rbenv
[[ -e "${HOME}/.dcp/rbenvrc" ]] &&
  source "${HOME}/.dcp/rbenvrc"
# Load aliases, local scripts, environment
[[ -e "${HOME}/.dcp/initrc" ]] &&
  source "${HOME}/.dcp/initrc"

# Set prompt
dcp_set_prompt

# 'Command not found' hook for Arch Linux
[[ -s "/usr/share/doc/pkgfile/command-not-found.bash" ]] &&
  source "/usr/share/doc/pkgfile/command-not-found.bash"
