export DCP="${HOME}/.dcp"
export ZSH="${HOME}/.oh-my-zsh"
export DISABLE_AUTO_UPDATE="true"

# Disable nasty % sign at end of output when there's no newline
export PROMPT_EOL_MARK=""

# Set up environment
. "${DCP}/lib/env.sh"

# Make sure we have our two spots in fpath
readonly USER_ZSH_FUNCTIONS="${XDG_DATA_HOME:-${HOME}/.local/share}/zsh/site-functions"

if [[ ! -e "${USER_ZSH_FUNCTIONS}" ]]; then
  mkdir -p "${USER_ZSH_FUNCTIONS}"
fi

fpath=("${USER_ZSH_FUNCTIONS}" "${DCP}/share/zsh/site-functions" "${fpath[@]}")

# Set oh-my-zsh theme
if [[ -s "${DCP_CONFIG_DIR}/zsh-theme" ]]; then
  export ZSH_THEME="$(cat "${DCP_CONFIG_DIR}/zsh-theme")"
else
  export ZSH_THEME="dpoggi"
fi
