export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="dpoggi"
export DISABLE_UPDATE_PROMPT="true"
plugins=(gem heroku npm nyan pip powder)
[[ -s "$HOME/.dcp/common" ]] && source "$HOME/.dcp/common"
[[ -s "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"
