export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="dpoggi"

plugins=(mysql-macports node npm osx pip rails rails3 rvm)

[[ -s "$ZSH/oh-my-zsh.sh" ]] &&
  source "$ZSH/oh-my-zsh.sh"

export PATH="$PATH:$HOME/.dcp/bin"

[[ -s "$HOME/.dcp/initrc" ]] &&
  source "$HOME/.dcp/initrc"
[[ -s "$HOME/.rvm/scripts/rvm" ]] &&
  source "$HOME/.rvm/scripts/rvm"
[[ -s "$HOME/.dcp/private" ]] &&
  source "$HOME/.dcp/private"
